linters:
  enable-all: true
  disable:
    - gomnd       # deprecated
    - execinquery # deprecated
    - exhaustruct
    - nlreturn
    - rowserrcheck
    - sqlclosecheck
    - wastedassign

run:
  timeout: 3m