version: '2'
linters:
  default: all
  disable:
    - exhaustruct
    - nlreturn
    - depguard
    - wsl
  settings:
    wsl_v5:
      disable:
        - assign
formatters:
  enable:
    - gci
    - gofmt
    - gofumpt
    - goimports
